# permissions for end users to edit workflowsdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workflowsdemo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-workflows
    app.kubernetes.io/part-of: operator-workflows
    app.kubernetes.io/managed-by: kustomize
  name: workflowsdemo-editor-role
rules:
- apiGroups:
  - dummy.grothesk.io
  resources:
  - workflowsdemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dummy.grothesk.io
  resources:
  - workflowsdemoes/status
  verbs:
  - get
