apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator-workflows.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Demo for GithubActions Workflows integration
  displayName: Workflows Demo Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - demo
  - devops
  - githubactions
  links:
  - name: Operator Workflows
    url: https://operator-workflows.domain
  maintainers:
  - email: malte.groth@posteo.net
    name: grothesk
  maturity: alpha
  provider:
    name: grothesk
    url: grothesk.io
  version: 0.0.0
