---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflowsdemos.dummy.grothesk.io
spec:
  group: dummy.grothesk.io
  names:
    kind: WorkflowsDemo
    listKind: WorkflowsDemoList
    plural: workflowsdemos
    singular: workflowsdemo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: WorkflowsDemo is the Schema for the workflowsdemos API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of WorkflowsDemo
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              desiredState:
                type: integer
          status:
            description: Status defines the observed state of WorkflowsDemo
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              currentState:
                type: integer
        type: object
    served: true
    storage: true
    subresources:
      status: {}
