name: Build and test the operator

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install krew
        uses: developer-guy/setup-krew@main
        with:
          krew-version: 'v0.4.4'

      - name: Install kuttl
        uses: actions-hub/kubectl@master
        with:
          args: krew install kuttl

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
