name: Build and test the operator

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install kuttl via krew
        run: |
          (
            set -x; cd "$(mktemp -d)" &&
            OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
            ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
            KREW="krew-${OS}_${ARCH}" &&
            curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
            tar zxvf "${KREW}.tar.gz" &&
            ./"${KREW}" install krew
          )
          echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' >> $HOME/.bashrc  # Modify for your shell
          export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
          kubectl krew version
          kubectl krew install kuttl
          kubectl kuttl version

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          make docker-build
      
      - name: Install and deploy operator
        run: make install deploy

      - name: Add /usr/local/bin to PATH
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          set -o pipefail
          echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' >> $HOME/.bashrc  # Modify for your shell
          export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
          bash hack/test.sh 2>&1 | tee /tmp/e2e-test.log
